// Precompute, for each daily number, the first salt whose round the PRO bot finishes under par on every hole.
// Output: src/sim/dailyTable.ts (so every browser gets the same, verified round).
import { writeFileSync } from 'node:fs';
import { DAILY_EPOCH, makeDaily } from '../src/sim/daily';
import { playHole } from './bot-lib';

const DAYS = Number(process.argv[2] ?? 120);
const salts: number[] = [];
const t0 = Date.now();
for (let n = 1; n <= DAYS; n++) {
  const date = new Date(DAILY_EPOCH + (n - 1) * 86400000 + 12 * 3600000);
  const local = new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), 12);
  let chosen = 0;
  for (let salt = 0; salt < 6; salt++) {
    const d = makeDaily(local, salt);
    const ok = d.holes.every((h) => playHole(h.hole, 'pro', 3, d.mods).strokes <= h.hole.par);
    if (ok) {
      chosen = salt;
      break;
    }
    chosen = salt + 1;
  }
  salts.push(Math.min(chosen, 5));
  if (n % 20 === 0) console.log(`day ${n}…`);
}
writeFileSync('src/sim/dailyTable.ts', `// Generated by tools/daily-table.ts — do not edit.\nexport const DAILY_SALTS: number[] = ${JSON.stringify(salts)};\n`);
console.log(`done ${DAYS} days in ${((Date.now() - t0) / 1000).toFixed(1)}s; salt histogram`, salts.reduce((h: Record<number, number>, s) => ((h[s] = (h[s] ?? 0) + 1), h), {}));
