// Picks a fair layout for every generated hole of the route and measures every hole's par with the bot
// (docs/diseno-v2.md §5.4). Writes src/sim/routeTable.ts.
// Usage: npx tsx tools/route-table.ts [--jobs=2] [--from=1] [--to=120]
import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { holeDef, ROUTE, ROUTE_LEN } from '../src/sim/route';
import { ROUTE_TABLE } from '../src/sim/routeTable';
import { measure, parFrom, verdict, type Measure } from './measure';

const arg = (k: string, d: string) => process.argv.find((a) => a.startsWith(`--${k}=`))?.split('=')[1] ?? d;
const jobs = Number(arg('jobs', '1'));
const part = arg('part', '');
const from = Number(arg('from', '1'));
const to = Math.min(ROUTE_LEN, Number(arg('to', String(ROUTE_LEN))));
const MAX_SALTS = 14;

interface Row {
  n: number;
  salt: number;
  par: number;
  m: Measure;
  tries: number;
  why: string;
}

function pick(n: number): Row {
  const L = ROUTE[n - 1];
  if (L.hand) {
    const m = measure(holeDef(n, 0), !!L.champ);
    return { n, salt: 0, par: parFrom(m), m, tries: 1, why: 'hand' };
  }
  let best: Row | null = null;
  let bestBad = Infinity;
  for (let salt = 0; salt < MAX_SALTS; salt++) {
    const def = holeDef(n, salt);
    const m = measure(def, L.champ);
    const v = verdict(m, L);
    const row: Row = { n, salt, par: parFrom(m), m, tries: salt + 1, why: v.why };
    if (v.ok) return row;
    if (v.bad < bestBad) {
      bestBad = v.bad;
      best = row;
    }
  }
  return { ...best!, why: `best of ${MAX_SALTS}: ${best!.why}` };
}

function line(r: Row): string {
  const L = ROUTE[r.n - 1];
  const tag = L.intro ? 'intro' : L.champ ? 'CUP' : L.hand ? 'hand' : '';
  return `L${String(r.n).padEnd(3)} ${L.course.padEnd(8)} ${tag.padEnd(5)} d=${L.d.toFixed(2)} salt ${String(r.salt).padStart(2)} par ${r.par}  casual ${r.m.casualMean.toFixed(2)} [${r.m.casual.join(' ')}]  pro [${r.m.pro.join(' ')}]  ${r.why}`;
}

async function main() {
  if (jobs > 1 && !part) {
    const dir = mkdtempSync(join(tmpdir(), 'route-'));
    const runs = Array.from({ length: jobs }, (_, k) => {
      const out = join(dir, `part${k}.json`);
      return new Promise<Row[]>((res, rej) => {
        const p = spawn(process.execPath, [...process.execArgv, process.argv[1], `--part=${k}/${jobs}`, `--from=${from}`, `--to=${to}`, `--out=${out}`], { stdio: ['ignore', 'inherit', 'inherit'] });
        p.on('exit', (code) => (code === 0 ? res(JSON.parse(readFileSync(out, 'utf8'))) : rej(new Error(`part ${k} failed`))));
      });
    });
    const rows = (await Promise.all(runs)).flat().sort((a, b) => a.n - b.n);
    write(rows);
    return;
  }
  const [k, N] = part ? part.split('/').map(Number) : [0, 1];
  const rows: Row[] = [];
  for (let n = from; n <= to; n++) {
    if ((n - from) % N !== k) continue;
    const r = pick(n);
    rows.push(r);
    console.log(line(r));
  }
  const out = arg('out', '');
  if (out) writeFileSync(out, JSON.stringify(rows));
  else write(rows);
}

function write(rows: Row[]) {
  const table: ([number, number] | undefined)[] = [];
  for (let n = 1; n <= ROUTE_LEN; n++) table[n - 1] = ROUTE_TABLE[n - 1];
  for (const r of rows) table[r.n - 1] = [r.salt, r.par];
  const body = table.map((t) => (t ? `[${t[0]}, ${t[1]}]` : 'undefined')).join(',\n  ');
  writeFileSync(
    new URL('../src/sim/routeTable.ts', import.meta.url),
    `// Generated by tools/route-table.ts — do not edit by hand.\n// Per hole of the route: [layout salt, par measured with the bot].\nexport const ROUTE_TABLE: ([number, number] | undefined)[] = [\n  ${body},\n];\n`,
  );
  const pars = rows.map((r) => r.par);
  console.log(`\n${rows.length} holes · pars ${[2, 3, 4, 5].map((p) => `${p}:${pars.filter((x) => x === p).length}`).join(' ')} · not ideal: ${rows.filter((r) => r.why.startsWith('best')).length}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
